### ISSUE TITLE
Atlas and Neural Ontology

### ISSUE THREAD

**Issue by vborghe** [neurocausal/neurocausal#4]
@pinheirochagas is the lead on this issue 🙏 
Steps:

- [ ] chose reference atlas
- [ ] establish mapping from more-vague terms to the atlas
- [ ] look for tools to cross-map between atlases
- [ ] look for tools to map from voxels to the chosen atlas

**Comment by pinheirochagas** [comment]
Hi, this tool neuroparc might be a very good solution: 
https://github.com/neurodata/neuroparc.
paper: 
https://www.nature.com/articles/s41597-021-00849-3.pdf?proof=t%C2%A0
I'm gonna explore it and report back.

**Comment by pinheirochagas** [comment]
To define the base atlas, we need to:

- Select the clinical papers. 
- Count the frequency of atlases. 
- Select the atlas that is mentioned in most studies as the base atlas. 
(probably Harvard-Oxford cortical and subcortical structural atlases or
WFU pickatlas - labels and Broadman areas). 
- Count how many other atlases are mentioned.
- If just a couple more, do a manual conversion across regions to the base atlas. 
- If a variety, we must choose a method to convert from labels to MNI coordinates to map to the base atlas. 
(this will required some decisions, such as which coordinate to use, centroid?)

**Comment by vborghe** [comment]
See https://github.com/neurocausal/neurocausal_meta/issues/12
